services:
  ygoapi:
    build:
      context: .
      dockerfile: api/YGOApi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      # Alterado para o formato do PostgreSQL (Porta padrão 5432)
      - ConnectionStrings__CardConnection=Host=db;Port=5432;Database=cards_db;Username=postgres;Password=rootpass;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - ygonet

  deck-builder-interface:
    build:
      context: ./deck-builder-interface
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ygoapi
    networks:
      - ygonet

  db:
    # Alterado de mysql:8.0 para postgres (recomendo a versão 15 ou 16)
    image: postgres:16-alpine
    restart: always
    environment:
      # Variáveis específicas do PostgreSQL
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: cards_db
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # O caminho interno do Postgres é diferente do MySQL
    networks:
      - ygonet

volumes:
  db_data:
    # O Docker criará um novo volume limpo para o Postgres

networks:
  ygonet:
    driver: bridge
