// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YGOApi.Data;

#nullable disable

namespace YGOApi.Migrations
{
    [DbContext(typeof(WriteContext))]
    [Migration("20260509165524_AdicionandoGalera")]
    partial class AdicionandoGalera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "card_atribute", new[] { "dark", "light", "earth", "water", "fire", "wind", "divine" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "card_ban_status", new[] { "unlimited", "semi_limited", "limited", "banned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "card_race", new[] { "aqua", "beast", "beast_warrior", "cyberse", "dinosaur", "divine_beast", "dragon", "fairy", "fiend", "fish", "insect", "ilusion", "machine", "plant", "psychic", "pyro", "reptile", "rock", "sea_serpent", "spellcaster", "thunder", "warrior", "winged_beast", "wyrm", "zombie" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "card_sub_type", new[] { "normal", "effect", "fusion", "ritual", "synchro", "xyz", "link", "pendulum", "continuous", "field", "equipament", "quick", "counter" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "card_type", new[] { "monster", "spell", "trap" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "admin", "player" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YGOApi.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Archetype")
                        .HasColumnType("text");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer");

                    b.Property<int?>("Attribute")
                        .HasColumnType("integer");

                    b.Property<int>("BanStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Collection")
                        .HasColumnType("text");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrlSmall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("LinkMarkers")
                        .HasColumnType("text");

                    b.Property<int?>("LinkRating")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Passcode")
                        .HasColumnType("integer");

                    b.Property<int?>("PendulumScale")
                        .HasColumnType("integer");

                    b.Property<int?>("Race")
                        .HasColumnType("integer");

                    b.Property<int>("SubType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("YGOApi.Models.CardCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("CardCollections");
                });

            modelBuilder.Entity("YGOApi.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeckCover")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("YGOApi.Models.DeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("YGOApi.Models.Galera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("Galeras");
                });

            modelBuilder.Entity("YGOApi.Models.GaleraCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("GaleraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardCollectionId");

                    b.HasIndex("GaleraId");

                    b.ToTable("GaleraCollections");
                });

            modelBuilder.Entity("YGOApi.Models.PlayerCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCollection");
                });

            modelBuilder.Entity("YGOApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YGOApi.Models.UserGalera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GaleraId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasMaxLength(60)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserGalera");
                });

            modelBuilder.Entity("YGOApi.Models.Card", b =>
                {
                    b.HasOne("YGOApi.Models.CardCollection", "CardCollection")
                        .WithMany()
                        .HasForeignKey("CollectionId");

                    b.Navigation("CardCollection");
                });

            modelBuilder.Entity("YGOApi.Models.Deck", b =>
                {
                    b.HasOne("YGOApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YGOApi.Models.DeckCard", b =>
                {
                    b.HasOne("YGOApi.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YGOApi.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("YGOApi.Models.GaleraCollection", b =>
                {
                    b.HasOne("YGOApi.Models.CardCollection", "CardCollection")
                        .WithMany()
                        .HasForeignKey("CardCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YGOApi.Models.Galera", "Galera")
                        .WithMany()
                        .HasForeignKey("GaleraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardCollection");

                    b.Navigation("Galera");
                });

            modelBuilder.Entity("YGOApi.Models.PlayerCollection", b =>
                {
                    b.HasOne("YGOApi.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YGOApi.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("YGOApi.Models.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });
#pragma warning restore 612, 618
        }
    }
}
